### ISSUE TITLE
Plugin reading gearset name wrong

### ISSUE THREAD

**Issue by VariableVixen** [maributt/auto-umbrellaplus#1]
I have a gearset named `Sage` and whenever the plugin reads it - setting a new auto-umbrella for it, switching to it and getting the chat message, etc - the plugin seems to read the name as `Sagelogian` instead. It doesn't seem to actually be _breaking_ anything, but it might be indicative of an issue somewhere that could become a problem, so I thought I'd report it.

**Comment by VariableVixen** [comment]
Update: `Reaper` is read as `Reaperar` too. `Red Mage`, `Dancer`, `Machinist`, `Ninja`, `Botanist`, `Miner`, and `Fisher` are all read correctly, if that helps.

**Comment by maributt** [comment]
Hi! Thanks for bringing it up!
I'm unable to recreate the issue with my own gearset setup, even looking at the code I can't exactly pinpoint what might've lead to this...
As an attempt to fix the issue I've tried altering how the strings are read/cleaned up 
Let me know if the issue persists, if it does, could you get back to me with a picture of your gearsets? (to get an idea of which order they're in to correlate it to what you were describing)
Thanks!

**Comment by VariableVixen** [comment]
I just updated to v23.7.3.0 and tried both gearsets, and it seems to be fixed now!
