### ISSUE TITLE
Update for Dawntrail?

### ISSUE THREAD

**Issue by cactuschef3** [maributt/auto-umbrellaplus#2]
was just wondering if this plugin is planned to be updated eventually, I was looking for exactly this feature and yours is the only plugin for it i've found :)

**Comment by maributt** [comment]
of course!! i'm in the process of updating it right now, should be good to go very soon, thanks for the interest ✌️

**Comment by maributt** [comment]
just pushed the update, let me know in another issue if anything's wrong with it 👍
